server:
  port: 9090

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root   #你本地的数据库用户名
    password: 123123123 #你本地的数据库密码
#    url: jdbc:mysql://localhost:3306/xm-blog?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    url: jdbc:mysql://${ip}:3306/xm-blog?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  redis:
    host: 47.98.43.176
    password: jjxian
    port: 6379
#  邮件推送
  mail:
    host: smtp.qq.com # 此处使用的是qq邮箱进行邮件发送
    protocol: smtp
    username: 2451999059@qq.com
    password: hserudvmqgejdiia
    default-encoding: UTF-8 #编码风格

    nickname: 技术研习中心
    properties:
      mail.smtp.auth: true #启用SMTP服务器的身份验证，这是为了确保只有合法用户可以发送邮件。
      mail.smtp.starttls.enable: #启用TLS加密，这是为了确保邮件传输的安全性。
      mail.smtp.starttls.required: true #要求使用TLS加密，如果连接不是通过TLS加密传输，则连接将失败。
#上线加上以下信息，阿里云禁止25端口
#      mail:
#        smtp:
#          ssl:
#            enable: true
#          socketFactory:
#            port: 465
#            class: javax.net.ssl.SSLSocketFactory


## 配置mybatis实体和xml映射
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.xian.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true

#配置mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xian.entity # 扫描包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false # 是否开启二级缓存
  global-config:
    db-config:
      id-type: assign_id # id为雪花算法生成

# 分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

ip: localhost

minio:
  accessKey: minio
  secretKey: minio123
  bucket: xian-blog
  endpoint: http://47.98.43.176:9000
  readPath: http://47.98.43.176:9000

